name: Matrix build

on: [push,pull_request,workflow_dispatch]

jobs:
  greet-matrix:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-12 ]
        name: [ "Anna", "John", "Denzel" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Greet
        run: |
          mkdir -p artifacts
           ./hello.sh "${{ matrix.name }} on $(uname)"| tee artifacts/greet

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: greet-artifacts
          path: artifacts
