name: Matrix build

on: [push, pull_request, workflow_dispatch]

jobs:
  greet-matrix:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-12 ]
        name: [ "Anna", "John", "Denzel" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Greet
        run: |
          mkdir -p artifacts
          who=${{ matrix.name }}
          where=$(uname)
          ./hello.sh "$who on $where"| tee artifacts/greet-$who-$where

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: greet-artifacts
          path: artifacts

  print-summary:
    needs: greet-matrix
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@master
        with:
          name: greet-artifacts
          path: artifacts
      - run: |
          echo "| Greetings sent |" >> $GITHUB_STEP_SUMMARY
          echo "| -------------- |" >> $GITHUB_STEP_SUMMARY
          for i in artifacts/*
          do
              echo "| $(cat $i) |" >> $GITHUB_STEP_SUMMARY
          done
          echo "![png](https://static.wikia.nocookie.net/linux/images/a/af/Tux.png/revision/latest?cb=20070422102946&path-prefix=pl)" >> $GITHUB_STEP_SUMMARY
