name: Simple test

on: [push, pull_request, workflow_dispatch]

jobs:
  simple-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Greet
        run: |
           ./hello.sh user
